### ISSUE TITLE
Cannot load M3U8: Crossdomain Access Denied

### ISSUE THREAD

**Issue by Andrroid88** [marshallthornton/Twitch.tv-Plex-Plugin#10] opened 2014-01-13 00:14 UTC
After installing this plugin, the twitch channel appears on all of my devices (tablet, phone, http://plex.tv/web/app). Unfortunately, when I try to play a channel from the tablet/phone, the app simply buffers and when I try to play a channel from http://plex.tv/web/app, I encounter the error "Cannot load M3U8: Crossdomain Access Denied.

**Comment by redfellow** [comment] 2014-01-15 21:33
I also can confirm this. I downloaded the plugin so that I could Chromecast it via plex.tv/web/app to my TV instead of using Tab Casting.

The plugin works if you play content via localhost, but then you cannot cast it to your TV.

**Comment by marshallthornton** [comment] 2014-01-16 00:37
This is a duplicate of #9 and we can't really fix it since the issue is caused by the crossdomain.xml that twitch.tv is sending to the flash player.

**Closed as completed by marshallthornton** 2014-01-16 00:37 UTC

**Comment by stevenroose** [comment] 2014-08-01 16:35
Why does the XBMC plugin for Twitch work without a problem then?

Isn't it possible to get the Twitch stream as a raw video stream instead of flash? And just use an HTML5 video tag to show the stream so that the browser can use it's own video player for it?

**Comment by deezit** [comment] 2014-11-28 07:05
On your modem/router or on your Windows hosts file add something like this :
plex.newjtv.com YOUR_PLEX_IP

and access plex by this url : http://plex.newjtv.com:32400/web/

Flash will see plex.newjtv.com and the crossdomain will work.
